In [1]:
##import of numpy

In [2]:
import numpy as np

In [3]:
#array of 10 zero

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#array of 10 fives

In [7]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
#an array of the integers from 10 to 50


In [82]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
#an array of all the even integers from 10 to 50

In [83]:
arr2=np.arange(10,51,2)
arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
#a 3x3 matrix with values ranging from 0 to 8

In [16]:
arr3=np.arange(0,9)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
arr3=arr3.reshape(3,3)
arr3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#Create a 3x3 identity matrix

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# NumPy to generate a random number between 0 and 1

In [26]:
np.random.rand(1)

array([0.6335242])

In [ ]:
#NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [27]:
np.random.randn(25)

array([-5.07973925e-02, -5.55209175e-01,  7.23022511e-01, -1.57052824e-01,
        6.01338075e-01, -3.17820706e-01, -1.79513833e-01, -4.03100806e-01,
        2.11197440e-01,  1.64374830e+00, -4.06701354e-01,  5.64691242e-01,
        4.80010015e-01,  1.47999779e+00,  9.17776992e-01, -1.04864539e+00,
        4.77640405e-04, -2.96728991e+00,  2.43703857e+00,  1.37610508e+00,
        1.14721732e+00, -3.43484234e-01, -7.41001794e-01,  1.18780495e+00,
        5.44467189e-01])

In [ ]:
#Create the following matrix:

In [36]:
arr4= np.arange(1,101)

In [37]:
arr4=arr4.reshape(10,10)

In [40]:
arr4
arr4/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# array of 20 linearly spaced points between 0 and 1

In [42]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
#you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [44]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
arr1=np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
arr1[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [53]:
arr1[3,4]

20

In [57]:
arr1[3,4:]

array([20])

In [58]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [61]:
arr[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [62]:
arr[4:]

array([[21, 22, 23, 24, 25]])

In [64]:
arr[4:,0:]

array([[21, 22, 23, 24, 25]])

In [65]:
arr[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
#Get the sum of all the values in mat

In [69]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [70]:
arr.sum()

325

In [ ]:
#Get the standard deviation of the values in mat

In [71]:
arr.std()

7.211102550927978

In [ ]:
#Get the sum of all the columns in mat

In [74]:
arr.sum().std()

0.0

In [ ]:
###Get the sum of all the columns in mat(not getting 15)

In [78]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [79]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [80]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [81]:
arr.sum(axis=1)

array([ 15,  40,  65,  90, 115])